// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

// Stores user feedback submissions with ratings and comments
type FeedbackFeedback struct {
	// Unique identifier for the feedback submission
	ID uuid.UUID `db:"id"`
	// Rating value from 1 to 5 stars
	Rating int32 `db:"rating"`
	// Free-text feedback comment (1-1000 characters)
	Comment string `db:"comment"`
	// Timestamp when the feedback was submitted
	CreatedAt time.Time `db:"created_at"`
	// Timestamp when the feedback was last updated
	UpdatedAt time.Time `db:"updated_at"`
	// Timestamp when the feedback was soft-deleted (NULL if not deleted)
	DeletedAt *time.Time `db:"deleted_at"`
}

// Stores user accounts for authentication and authorization
type User struct {
	// Unique identifier for the user
	ID uuid.UUID `db:"id"`
	// User email address (unique, normalized to lowercase)
	Email string `db:"email"`
	// Hashed password (never store plain text)
	PasswordHash string `db:"password_hash"`
	// Array of user roles (e.g., ["user", "admin"])
	Roles []string `db:"roles"`
	// User account status: active, inactive, or suspended
	Status string `db:"status"`
	// Timestamp when the user account was created
	CreatedAt time.Time `db:"created_at"`
	// Timestamp when the user account was last updated
	UpdatedAt time.Time `db:"updated_at"`
	// Timestamp when the user account was soft-deleted (NULL if not deleted)
	DeletedAt *time.Time `db:"deleted_at"`
}
