-- +goose Up
-- +goose StatementBegin

-- Create default admin user, this is not the best approach but works for showcasing the system.
-- In a prod environment, the initial should be auto generated by the system and outputed as a secret.
-- Email: admin@mail.com
-- Password: adminpass (hashed with bcrypt)
-- Role: admin
INSERT INTO feedback.users (
    id,
    email,
    password_hash,
    roles,
    status,
    created_at,
    updated_at,
    deleted_at
) VALUES (
    uuid_generate_v4(),
    'admin@mail.com',
    '$2a$10$zwtqTvBhIFTY3HB53TEuCuCJ7/mpfmy7oL45IDJVb8pPetqycVEEu', -- bcrypt hash of "adminpass"
    ARRAY['admin']::TEXT[],
    'active',
    NOW(),
    NOW(),
    NULL
)
ON CONFLICT (email) DO NOTHING; -- Prevent duplicate if migration is run multiple times

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

-- Remove default admin user
DELETE FROM feedback.users WHERE email = 'admin@mail.com';

-- +goose StatementEnd
