// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_topic.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTopic = `-- name: CreateTopic :one
INSERT INTO feedback.analysis_topics (
    id,
    analysis_id,
    topic_name,
    description,
    feedback_count,
    sentiment,
    created_at,
    updated_at
) VALUES (
    $1,  -- id
    $2,  -- analysis_id
    $3,  -- topic_name
    $4,  -- description
    $5,  -- feedback_count
    $6,  -- sentiment
    $7,  -- created_at
    $8   -- updated_at
)
RETURNING id, analysis_id, topic_name, description, feedback_count, sentiment, created_at, updated_at
`

type CreateTopicParams struct {
	ID            uuid.UUID         `db:"id"`
	AnalysisID    uuid.UUID         `db:"analysis_id"`
	TopicName     string            `db:"topic_name"`
	Description   string            `db:"description"`
	FeedbackCount int32             `db:"feedback_count"`
	Sentiment     FeedbackSentiment `db:"sentiment"`
	CreatedAt     time.Time         `db:"created_at"`
	UpdatedAt     time.Time         `db:"updated_at"`
}

func (q *Queries) CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error) {
	row := q.db.QueryRow(ctx, createTopic,
		arg.ID,
		arg.AnalysisID,
		arg.TopicName,
		arg.Description,
		arg.FeedbackCount,
		arg.Sentiment,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.AnalysisID,
		&i.TopicName,
		&i.Description,
		&i.FeedbackCount,
		&i.Sentiment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
