// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_analyzed_feedbacks.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAnalyzedFeedback = `-- name: CreateAnalyzedFeedback :exec
INSERT INTO feedback.analyzed_feedbacks (
    analysis_id,
    feedback_id,
    created_at
) VALUES (
    $1,  -- analysis_id
    $2,  -- feedback_id
    $3   -- created_at
)
ON CONFLICT (analysis_id, feedback_id) DO NOTHING
`

type CreateAnalyzedFeedbackParams struct {
	AnalysisID uuid.UUID `db:"analysis_id"`
	FeedbackID uuid.UUID `db:"feedback_id"`
	CreatedAt  time.Time `db:"created_at"`
}

func (q *Queries) CreateAnalyzedFeedback(ctx context.Context, arg CreateAnalyzedFeedbackParams) error {
	_, err := q.db.Exec(ctx, createAnalyzedFeedback, arg.AnalysisID, arg.FeedbackID, arg.CreatedAt)
	return err
}

const getFeedbackIDsByAnalysisID = `-- name: GetFeedbackIDsByAnalysisID :many
SELECT feedback_id FROM feedback.analyzed_feedbacks
WHERE analysis_id = $1
`

func (q *Queries) GetFeedbackIDsByAnalysisID(ctx context.Context, analysisID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getFeedbackIDsByAnalysisID, analysisID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var feedback_id uuid.UUID
		if err := rows.Scan(&feedback_id); err != nil {
			return nil, err
		}
		items = append(items, feedback_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
