// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_topic_assignments.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTopicAssignment = `-- name: CreateTopicAssignment :exec
INSERT INTO feedback.feedback_topic_assignments (
    id,
    analysis_id,
    feedback_id,
    topic_id,
    created_at
) VALUES (
    $1,  -- id
    $2,  -- analysis_id
    $3,  -- feedback_id
    $4,  -- topic_id
    $5   -- created_at
)
ON CONFLICT (analysis_id, feedback_id, topic_id) DO NOTHING
`

type CreateTopicAssignmentParams struct {
	ID         uuid.UUID `db:"id"`
	AnalysisID uuid.UUID `db:"analysis_id"`
	FeedbackID uuid.UUID `db:"feedback_id"`
	TopicID    uuid.UUID `db:"topic_id"`
	CreatedAt  time.Time `db:"created_at"`
}

func (q *Queries) CreateTopicAssignment(ctx context.Context, arg CreateTopicAssignmentParams) error {
	_, err := q.db.Exec(ctx, createTopicAssignment,
		arg.ID,
		arg.AnalysisID,
		arg.FeedbackID,
		arg.TopicID,
		arg.CreatedAt,
	)
	return err
}
