// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_topic.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTopicAnalysis = `-- name: CreateTopicAnalysis :one
INSERT INTO feedback.analysis_topics (
    id,
    analysis_id,
    topic_enum,
    summary,
    feedback_count,
    sentiment,
    created_at,
    updated_at
) VALUES (
    $1,  -- id
    $2,  -- analysis_id
    $3,  -- topic_enum
    $4,  -- summary
    $5,  -- feedback_count
    $6,  -- sentiment
    $7,  -- created_at
    $8   -- updated_at
)
RETURNING id, analysis_id, feedback_count, sentiment, created_at, updated_at, topic_enum, summary
`

type CreateTopicAnalysisParams struct {
	ID            uuid.UUID         `db:"id"`
	AnalysisID    uuid.UUID         `db:"analysis_id"`
	TopicEnum     FeedbackTopicEnum `db:"topic_enum"`
	Summary       string            `db:"summary"`
	FeedbackCount int32             `db:"feedback_count"`
	Sentiment     FeedbackSentiment `db:"sentiment"`
	CreatedAt     time.Time         `db:"created_at"`
	UpdatedAt     time.Time         `db:"updated_at"`
}

func (q *Queries) CreateTopicAnalysis(ctx context.Context, arg CreateTopicAnalysisParams) (Topic, error) {
	row := q.db.QueryRow(ctx, createTopicAnalysis,
		arg.ID,
		arg.AnalysisID,
		arg.TopicEnum,
		arg.Summary,
		arg.FeedbackCount,
		arg.Sentiment,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.AnalysisID,
		&i.FeedbackCount,
		&i.Sentiment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TopicEnum,
		&i.Summary,
	)
	return i, err
}
