// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getAnalysisByID = `-- name: GetAnalysisByID :one
SELECT id, previous_analysis_id, period_start, period_end, feedback_count, new_feedback_count, overall_summary, sentiment, key_insights, model, tokens, analysis_duration_ms, status, failure_reason, created_at, completed_at FROM feedback.analyses
WHERE id = $1
`

func (q *Queries) GetAnalysisByID(ctx context.Context, id uuid.UUID) (Analysis, error) {
	row := q.db.QueryRow(ctx, getAnalysisByID, id)
	var i Analysis
	err := row.Scan(
		&i.ID,
		&i.PreviousAnalysisID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.FeedbackCount,
		&i.NewFeedbackCount,
		&i.OverallSummary,
		&i.Sentiment,
		&i.KeyInsights,
		&i.Model,
		&i.Tokens,
		&i.AnalysisDurationMs,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getLatestAnalysis = `-- name: GetLatestAnalysis :one
SELECT id, previous_analysis_id, period_start, period_end, feedback_count, new_feedback_count, overall_summary, sentiment, key_insights, model, tokens, analysis_duration_ms, status, failure_reason, created_at, completed_at FROM feedback.analyses
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestAnalysis(ctx context.Context) (Analysis, error) {
	row := q.db.QueryRow(ctx, getLatestAnalysis)
	var i Analysis
	err := row.Scan(
		&i.ID,
		&i.PreviousAnalysisID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.FeedbackCount,
		&i.NewFeedbackCount,
		&i.OverallSummary,
		&i.Sentiment,
		&i.KeyInsights,
		&i.Model,
		&i.Tokens,
		&i.AnalysisDurationMs,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}
