// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_topics.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getFeedbackIDsByTopicID = `-- name: GetFeedbackIDsByTopicID :many
SELECT feedback_id FROM feedback.feedback_topic_assignments
WHERE topic_id = $1
`

func (q *Queries) GetFeedbackIDsByTopicID(ctx context.Context, topicID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getFeedbackIDsByTopicID, topicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var feedback_id uuid.UUID
		if err := rows.Scan(&feedback_id); err != nil {
			return nil, err
		}
		items = append(items, feedback_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopicsByAnalysisID = `-- name: GetTopicsByAnalysisID :many
SELECT id, analysis_id, topic_name, description, feedback_count, sentiment, created_at, updated_at FROM feedback.analysis_topics
WHERE analysis_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetTopicsByAnalysisID(ctx context.Context, analysisID uuid.UUID) ([]Topic, error) {
	rows, err := q.db.Query(ctx, getTopicsByAnalysisID, analysisID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topic{}
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.AnalysisID,
			&i.TopicName,
			&i.Description,
			&i.FeedbackCount,
			&i.Sentiment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
