// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: list.sql

package sqlc

import (
	"context"
)

const listAnalyses = `-- name: ListAnalyses :many
SELECT id, previous_analysis_id, period_start, period_end, feedback_count, new_feedback_count, overall_summary, sentiment, key_insights, model, tokens, analysis_duration_ms, status, failure_reason, created_at, completed_at FROM feedback.analyses
ORDER BY created_at DESC
`

func (q *Queries) ListAnalyses(ctx context.Context) ([]Analysis, error) {
	rows, err := q.db.Query(ctx, listAnalyses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Analysis{}
	for rows.Next() {
		var i Analysis
		if err := rows.Scan(
			&i.ID,
			&i.PreviousAnalysisID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.FeedbackCount,
			&i.NewFeedbackCount,
			&i.OverallSummary,
			&i.Sentiment,
			&i.KeyInsights,
			&i.Model,
			&i.Tokens,
			&i.AnalysisDurationMs,
			&i.Status,
			&i.FailureReason,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
