// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAnalysis(ctx context.Context, arg CreateAnalysisParams) (Analysis, error)
	CreateAnalyzedFeedback(ctx context.Context, arg CreateAnalyzedFeedbackParams) error
	CreateTopicAnalysis(ctx context.Context, arg CreateTopicAnalysisParams) (Topic, error)
	CreateTopicAssignment(ctx context.Context, arg CreateTopicAssignmentParams) error
	GetAnalysisByID(ctx context.Context, id uuid.UUID) (Analysis, error)
	GetFeedbackIDsByAnalysisID(ctx context.Context, analysisID uuid.UUID) ([]uuid.UUID, error)
	GetFeedbackIDsByTopicID(ctx context.Context, topicID uuid.UUID) ([]uuid.UUID, error)
	GetLatestAnalysis(ctx context.Context) (Analysis, error)
	GetTopicsByAnalysisID(ctx context.Context, analysisID uuid.UUID) ([]Topic, error)
	ListAnalyses(ctx context.Context) ([]Analysis, error)
	UpdateAnalysis(ctx context.Context, arg UpdateAnalysisParams) error
}

var _ Querier = (*Queries)(nil)
