// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const updateAnalysis = `-- name: UpdateAnalysis :exec
UPDATE feedback.analyses
SET
    overall_summary = $2,
    sentiment = $3,
    key_insights = $4,
    tokens = $5,
    status = $6,
    failure_reason = $7,
    completed_at = $8
WHERE id = $1
`

type UpdateAnalysisParams struct {
	ID             uuid.UUID              `db:"id"`
	OverallSummary string                 `db:"overall_summary"`
	Sentiment      FeedbackSentiment      `db:"sentiment"`
	KeyInsights    []string               `db:"key_insights"`
	Tokens         int32                  `db:"tokens"`
	Status         FeedbackAnalysisStatus `db:"status"`
	FailureReason  *string                `db:"failure_reason"`
	CompletedAt    *time.Time             `db:"completed_at"`
}

func (q *Queries) UpdateAnalysis(ctx context.Context, arg UpdateAnalysisParams) error {
	_, err := q.db.Exec(ctx, updateAnalysis,
		arg.ID,
		arg.OverallSummary,
		arg.Sentiment,
		arg.KeyInsights,
		arg.Tokens,
		arg.Status,
		arg.FailureReason,
		arg.CompletedAt,
	)
	return err
}
