// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeedback = `-- name: CreateFeedback :one
INSERT INTO feedback.feedbacks (
    id,
    user_id,
    rating,
    comment,
    created_at,
    updated_at,
    deleted_at
) VALUES (
    $1, -- id
    $2, -- user_id
    $3, -- rating
    $4, -- comment
    $5, -- created_at
    $6, -- updated_at
    $7  -- deleted_at
)
RETURNING id, rating, comment, created_at, updated_at, deleted_at, user_id
`

type CreateFeedbackParams struct {
	ID        uuid.UUID  `db:"id"`
	UserID    uuid.UUID  `db:"user_id"`
	Rating    int32      `db:"rating"`
	Comment   string     `db:"comment"`
	CreatedAt time.Time  `db:"created_at"`
	UpdatedAt time.Time  `db:"updated_at"`
	DeletedAt *time.Time `db:"deleted_at"`
}

func (q *Queries) CreateFeedback(ctx context.Context, arg CreateFeedbackParams) (Feedback, error) {
	row := q.db.QueryRow(ctx, createFeedback,
		arg.ID,
		arg.UserID,
		arg.Rating,
		arg.Comment,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	var i Feedback
	err := row.Scan(
		&i.ID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserID,
	)
	return i, err
}
