// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delete.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const deleteFeedback = `-- name: DeleteFeedback :execrows
UPDATE feedback.feedbacks
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) DeleteFeedback(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFeedback, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
