// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getFeedback = `-- name: GetFeedback :one
SELECT id, rating, comment, created_at, updated_at, deleted_at FROM feedback.feedbacks
WHERE id = $1
`

func (q *Queries) GetFeedback(ctx context.Context, id uuid.UUID) (Feedback, error) {
	row := q.db.QueryRow(ctx, getFeedback, id)
	var i Feedback
	err := row.Scan(
		&i.ID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
