// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: list.sql

package sqlc

import (
	"context"
)

const listFeedbacks = `-- name: ListFeedbacks :many
SELECT id, rating, comment, created_at, updated_at, deleted_at, user_id FROM feedback.feedbacks
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

func (q *Queries) ListFeedbacks(ctx context.Context, limit int32, offset int32) ([]Feedback, error) {
	rows, err := q.db.Query(ctx, listFeedbacks, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feedback{}
	for rows.Next() {
		var i Feedback
		if err := rows.Scan(
			&i.ID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
