// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

// Stores user feedback submissions with ratings and comments
type Feedback struct {
	// Unique identifier for the feedback submission
	ID uuid.UUID `db:"id"`
	// Rating value from 1 to 5 stars
	Rating int32 `db:"rating"`
	// Free-text feedback comment (1-1000 characters)
	Comment string `db:"comment"`
	// Timestamp when the feedback was submitted
	CreatedAt time.Time `db:"created_at"`
	// Timestamp when the feedback was last updated
	UpdatedAt time.Time `db:"updated_at"`
	// Timestamp when the feedback was soft-deleted (NULL if not deleted)
	DeletedAt *time.Time `db:"deleted_at"`
}
