// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateFeedback(ctx context.Context, arg CreateFeedbackParams) (Feedback, error)
	DeleteFeedback(ctx context.Context, id uuid.UUID) (int64, error)
	GetFeedback(ctx context.Context, id uuid.UUID) (Feedback, error)
	ListFeedbacks(ctx context.Context, limit int32, offset int32) ([]Feedback, error)
}

var _ Querier = (*Queries)(nil)
